# Generated by Django 5.1.7 on 2025-03-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_alter_trainee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='image',
            field=models.ImageField(upload_to='trainee/images/'),
        ),
    ]
