# Generated by Django 5.1.7 on 2025-03-14 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
        ('trainee', '0003_alter_trainee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='track',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='track.track'),
            preserve_default=False,
        ),
    ]
